name: "trigger-seed-cleanups"

on:
  push:
    branches:
      - seed-schema-testing

jobs:
  build:
    runs-on: python3

    steps:

      - name: Install Python dependencies
        run: pip install mysql-connector-python


      - name: Execute Python script
        run: python3 ./.github/workflows/goldenSeedClenup.py