name: "trigger-seed-cleanup"
run-name: "Dev build: ${{ github.ref_name }}"

on:
  workflow_dispatch:
    inputs:
      # Tracking inputs
      DB-hostName:
        description: 'Enter DB instance host'
        type: string


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace '3.x' with the Python version you want to use (e.g., '3.9')

      - name: Execute Python script
        run: python3 /Users/aera/Documents/seed-schema-db-scripts-mylocal/pythonLib