name: "trigger-seed-cleanup"
run-name: "Dev build: ${{ github.ref_name }}"

on:
  workflow_dispatch:
    inputs:
      # Tracking inputs
      DB-hostName:
        description: 'Enter DB instance host'
        type: string
env:
  COMPONENT_NAME: "seed-schema-db-scripts"

jobs:
  tracking:
    name: "Golden Seed Data cleanup"
    uses: aeratechnology/github-actions/.github/workflows/tracking-job.yaml@master
    with:
      upstream-job: ${{ inputs.upstream-job }}
      trace-id: ${{ inputs.trace-id }}

  build-and-publish:
    name: "discovery-be"
    uses: ./.github/workflows/build-and-publish.yaml
    with:
      pre-release-label: "dev"
    secrets: inherit