name: "trigger-seed-cleanups"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace '3.x' with the Python version you want to use (e.g., '3.9')

      - name: Install MySQL client
        run: sudo apt-get install -y libmysqlclient-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mysql-connector-python

      - name: Execute Python script
        run: python3 ./.github/workflows/goldenSeedClenup.py