name: "trigger-seed-cleanups"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: python3

    steps:
      - name: "Build setup"
        id: build-setup
        uses: aeratechnology/github-actions/BuildSetup@master
        with:
          component-name: "${{ env.COMPONENT_NAME }}"
          pre-release-label: "${{ inputs.pre-release-label }}"

      - name: Install MySQL client
        run: sudo apt-get install -y libmysqlclient-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mysql-connector-python


      - name: Execute Python script
        run: python3 ./.github/workflows/goldenSeedClenup.py